server:
  port: 8080
  address: 0.0.0.0
ita:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: digitalKids
    username: root
    password: 123456